'use strict';

/**
 * SMC API v3 JSON -> the normalized ticket shape `buildContext()` consumes.
 *
 * Mapped against the live OpenAPI 3.0 spec at `GET /v3/docs`
 * (Expedient IS Dev Team, API version 3.0.0, read 2026-09-15). Field names are
 * confirmed from `TicketResponse` / `TicketNoteResponse` / `ClientUserSimple`,
 * not guessed. The API is snake_case throughout.
 *
 * The output shape is the same one `inlineTicket()` in server.js produces from
 * a DOM scrape, so an API adapter and a DOM adapter stay interchangeable and
 * nothing downstream of `buildContext()` knows which one ran.
 */

const { redact } = require('./client');

/** Pull `.name` off a `*Simple` relation object, tolerating null. */
const nameOf = (rel) => (rel && typeof rel === 'object' && rel.name ? String(rel.name).trim() : '');

/** Pull `.id` off a `*Simple` relation object, or null. */
const idOf = (rel) => (rel && typeof rel === 'object' && rel.id != null && Number.isFinite(Number(rel.id)) ? Number(rel.id) : null);

/** Pull a human name off a UserSimple / UserContact, tolerating null. */
const personOf = (user) => {
  if (!user || typeof user !== 'object') return '';
  return String(user.full_name || user.username || '').trim();
};

const str = (value) => (value === null || value === undefined ? '' : String(value).trim());

/**
 * Classify a note's author as the customer or one of ours.
 *
 * This is the highest-stakes mapping in the file: `role` drives
 * `awaitingOurReply` in context.js, which decides whether One Pane drafts at
 * all. An analyst note misread as a customer note makes the tool answer a
 * question nobody asked.
 *
 * The v3 schema has no "is this person a customer" flag on a note - `created_by`
 * is a bare `UserSimple` of `{id, full_name, username}`. What it does have is a
 * separate ClientUser entity linking a `user_id` to a client, exposed per ticket
 * at `GET /tickets/{id}/contacts`. So authorship is resolved by set membership
 * against that list rather than by pattern-matching a name or a title.
 *
 * When the contact list could not be fetched, `clientUserIds` is null and every
 * human note degrades to 'system' - counted in the thread, never mistaken for a
 * customer asking us something. Guessing would be the worse failure: One Pane
 * drafting a reply to a question the customer never asked is precisely the
 * outcome the confidence gating exists to prevent.
 *
 * @param {object} note        TicketNoteResponse
 * @param {Set<number>|null} clientUserIds  user ids belonging to client contacts
 */
function classifyRole(note, clientUserIds) {
  // Status transitions are generated by SMC, not written by a person.
  if (note.is_status_change === true) return 'system';

  const authorId = note.created_by && note.created_by.id;
  if (authorId === undefined || authorId === null) return 'system';
  if (!clientUserIds) return 'system';

  return clientUserIds.has(Number(authorId)) ? 'client' : 'analyst';
}

/**
 * One `TicketNoteResponse` -> one normalized note.
 *
 * `visibility` is carried through as-is: context.js uses it to decide what the
 * customer can actually see, and inventing a default of 'All' for a note the
 * API marked internal would leak an internal note into a customer-facing draft.
 */
function toNote(note, clientUserIds) {
  return {
    author: personOf(note.created_by) || 'Unknown',
    role: classifyRole(note, clientUserIds),
    visibility: str(note.visibility) || 'All',
    at: str(note.created_at),
    body: str(note.body),
  };
}

/**
 * Synthesize the ticket's own `body` as its opening note.
 *
 * v3 keeps the text typed when a ticket is created on the ticket record
 * itself (`body`), separate from `TicketNoteResponse[]` - confirmed against
 * ticket 3808633, a brand-new test ticket with zero notes whose only content
 * was `body`. Without this, `toTicket()` silently dropped it and a fresh
 * ticket with no reply yet - exactly the case a first-draft tool matters most
 * for - normalized to an empty thread.
 *
 * Authorship is resolved the same way as any other note, via `classifyRole()`
 * against the ticket's own `created_by`, so a customer-opened ticket still
 * correctly reads as a `client` note rather than defaulting to `system`.
 */
function openingNote(record, clientUserIds) {
  const body = str(record.body);
  if (!body) return null;

  const role = classifyRole({ created_by: record.created_by, is_status_change: false }, clientUserIds);

  return {
    author: personOf(record.created_by) || 'Unknown',
    role,
    visibility: str(record.visibility) || 'All',
    at: str(record.created_at),
    body,
  };
}

/**
 * Synthesize the existing AI summary as an `ai` note.
 *
 * In the mock corpus the incumbent summarizer appears as a note with
 * `role: 'ai'`; in v3 it is two fields on the ticket itself. Rendering it back
 * into the thread keeps `latestAiSummary()` and `assessSummaryStaleness()` in
 * context.js working unchanged - and the API's own
 * `internal_summary_updated_at` is a real timestamp, which is strictly better
 * than the staleness heuristic those functions had to infer from note dates.
 */
function aiSummaryNote(ticket) {
  const body = str(ticket.internal_summary);
  if (!body) return null;

  return {
    author: 'SMC AI Summary',
    role: 'ai',
    visibility: 'Internal',
    at: str(ticket.internal_summary_updated_at),
    body,
  };
}

/**
 * Pick the contact to address the reply to.
 *
 * `ClientUserResponse.is_default` marks the client's primary contact and
 * `order` is its stated priority, so prefer those over list position.
 */
function primaryContact(contacts) {
  if (!Array.isArray(contacts) || !contacts.length) return '';

  const sorted = [...contacts].sort((a, b) => {
    if (Boolean(b.is_default) !== Boolean(a.is_default)) return b.is_default ? 1 : -1;
    return (a.order ?? 1e9) - (b.order ?? 1e9);
  });

  return personOf(sorted[0].user) || str(sorted[0].full_name);
}

/**
 * Client `user_id`s for a ticket's contacts.
 *
 * `ClientUserSimple` carries both its own `id` and the underlying `user_id`;
 * a note's `created_by.id` is the *user* id, so that is the one to match on.
 * Matching the wrong one silently classifies every customer note as analyst.
 *
 * @returns {Set<number>|null} null when the list is unavailable
 */
function clientUserIdSet(contacts) {
  if (!Array.isArray(contacts)) return null;

  const ids = new Set();
  for (const contact of contacts) {
    const userId = contact.user_id ?? (contact.user && contact.user.id);
    if (userId !== undefined && userId !== null) ids.add(Number(userId));
  }
  return ids;
}

/**
 * Map an SMC v3 ticket into the normalized shape.
 *
 * @param {object} ticket  TicketResponse
 * @param {object} [parts]
 * @param {object[]} [parts.notes]     TicketNoteResponse[], oldest first
 * @param {object[]} [parts.contacts]  ClientUser records for this ticket
 * @param {object[]} [parts.assets]    asset records for this ticket
 * @returns {object|null} null when there is not enough to work with
 */
function toTicket(ticket, parts = {}) {
  if (!ticket || typeof ticket !== 'object') return null;

  const record = ticket.data && !ticket.id ? ticket.data : ticket;
  if (!record.id && !record.subject) return null;

  const clientUserIds = clientUserIdSet(parts.contacts);

  const notes = (Array.isArray(parts.notes) ? parts.notes : [])
    .map((note) => toNote(note, clientUserIds));

  const opening = openingNote(record, clientUserIds);
  if (opening) notes.unshift(opening);

  notes.sort((a, b) => String(a.at).localeCompare(String(b.at)));

  const summary = aiSummaryNote(record);
  if (summary) notes.push(summary);

  const subject = str(record.subject);

  return {
    id: str(record.id),
    subject,
    title: subject,
    client: nameOf(record.client),
    // Ids let the ticket-history search (smc/history.js) filter exactly,
    // rather than by a name that may be spelled two ways.
    clientId: idOf(record.client),
    clientContact: primaryContact(parts.contacts),
    status: str(record.status),
    severity: str(record.severity),
    visibility: str(record.visibility) || 'All',
    queue: nameOf(record.queue),
    type: str(record.type),
    category: nameOf(record.category),
    categoryId: idOf(record.category),
    problem: nameOf(record.problem),
    problemId: idOf(record.problem),
    assignedTo: personOf(record.assigned_to),
    openedBy: personOf(record.created_by),
    created: str(record.created_at),
    lastUpdated: str(record.updated_at),
    facility: Array.isArray(record.facilities) && record.facilities.length ? nameOf(record.facilities[0]) : '',
    services: [],
    assets: (Array.isArray(parts.assets) ? parts.assets : []).map((a) => str(a.name || a.hostname)).filter(Boolean),
    relatedTickets: [],
    notes,
  };
}

/**
 * Non-identifying summary of what a mapping produced.
 *
 * Lets a caller confirm the adapter is working against a real ticket without
 * putting customer content into a log or a terminal: counts and field presence,
 * never note bodies. The subject is sampled because a wrong subject is the
 * fastest way to notice the wrong ticket was fetched.
 */
function mappingSummary(normalized) {
  if (!normalized) return { error: 'adapter returned null' };

  const empty = Object.entries(normalized)
    .filter(([, v]) => v === '' || (Array.isArray(v) && !v.length))
    .map(([k]) => k);

  return {
    id: normalized.id,
    subjectSample: redact(normalized.subject).slice(0, 60),
    emptyFields: empty,
    noteCount: normalized.notes.length,
    roleCounts: normalized.notes.reduce((acc, n) => {
      acc[n.role] = (acc[n.role] || 0) + 1;
      return acc;
    }, {}),
    lastNoteRole: normalized.notes.length ? normalized.notes[normalized.notes.length - 1].role : null,
  };
}

/**
 * Structural summary of a payload: keys and types, not values.
 *
 * Kept from the discovery pass - still the right tool for looking at an
 * endpoint nobody has mapped yet without pulling customer data into a terminal.
 */
function describeShape(value, depth = 0) {
  if (value === null) return 'null';
  if (Array.isArray(value)) {
    if (!value.length) return 'array(0)';
    return { [`array(${value.length})`]: depth >= 3 ? '...' : describeShape(value[0], depth + 1) };
  }

  if (typeof value === 'object') {
    if (depth >= 3) return '{...}';
    const out = {};
    for (const key of Object.keys(value).slice(0, 60)) out[key] = describeShape(value[key], depth + 1);
    return out;
  }

  if (typeof value === 'string') return value.length > 40 ? `string(${value.length})` : `string: ${redact(value)}`;
  return typeof value;
}

module.exports = { toTicket, toNote, openingNote, classifyRole, mappingSummary, describeShape };
